// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MyAvaloniaApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure;

#nullable disable

namespace MyAvaloniaApp.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260313000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.UseIdentityByDefaultColumns();

        modelBuilder.Entity("MyAvaloniaApp.Models.Personnel", b =>
        {
            b.Property<int>("Ppr")
                .HasColumnType("integer")
                .HasColumnName("ppr");

            b.Property<DateTime?>("AncAdm").HasColumnType("timestamp with time zone").HasColumnName("anc_adm");
            b.Property<DateTime?>("AncEchelon").HasColumnType("timestamp with time zone").HasColumnName("anc_echelon");
            b.Property<DateTime?>("AncGrade").HasColumnType("timestamp with time zone").HasColumnName("anc_grade");
            b.Property<string>("Adresse").HasColumnType("text").HasColumnName("adresse");
            b.Property<string>("AdresseElec").HasColumnType("text").HasColumnName("adresse_elec");
            b.Property<bool?>("AffectationPrinc").HasColumnType("boolean").HasColumnName("affectation_princ");
            b.Property<bool?>("Affilie").HasColumnType("boolean").HasColumnName("affilie");
            b.Property<int?>("AnNais").HasColumnType("integer").HasColumnName("an_nais");
            b.Property<string>("CdCadre").HasColumnType("text").HasColumnName("cd_cadre");
            b.Property<string>("CdDipp").HasColumnType("text").HasColumnName("cd_dipp");
            b.Property<string>("CdDips").HasColumnType("text").HasColumnName("cd_dips");
            b.Property<string>("CdDiscip").HasColumnType("text").HasColumnName("cd_discip");
            b.Property<string>("CdGrade").HasColumnType("text").HasColumnName("cd_grade");
            b.Property<string>("CdLastEtab").HasColumnType("text").HasColumnName("cd_last_etab");
            b.Property<string>("CdLastFonc").HasColumnType("text").HasColumnName("cd_last_fonc");
            b.Property<string>("CdNation").HasColumnType("text").HasColumnName("cd_nation");
            b.Property<string>("CdPosition").HasColumnType("text").HasColumnName("cd_position");
            b.Property<string>("CdStatut").HasColumnType("text").HasColumnName("cd_statut");
            b.Property<string>("CiNa").HasColumnType("text").HasColumnName("cina");
            b.Property<int?>("CiNn").HasColumnType("integer").HasColumnName("cinn");
            b.Property<int?>("CodePostal").HasColumnType("integer").HasColumnName("code_postal");
            b.Property<DateTime?>("DateAffil").HasColumnType("timestamp with time zone").HasColumnName("dateaffil");
            b.Property<DateTime?>("DatePosition").HasColumnType("timestamp with time zone").HasColumnName("date_position");
            b.Property<DateTime?>("DateRec").HasColumnType("timestamp with time zone").HasColumnName("date_rec");
            b.Property<DateTime?>("DateSitFam").HasColumnType("timestamp with time zone").HasColumnName("date_sitfam");
            b.Property<DateTime?>("DtCadre").HasColumnType("timestamp with time zone").HasColumnName("dt_cadre");
            b.Property<DateTime?>("DtDipProf").HasColumnType("timestamp with time zone").HasColumnName("dt_dipprof");
            b.Property<DateTime?>("DtDipScol").HasColumnType("timestamp with time zone").HasColumnName("dt_dipscol");
            b.Property<DateTime?>("DtEchelon").HasColumnType("timestamp with time zone").HasColumnName("dt_echelon");
            b.Property<DateTime?>("DtGrade").HasColumnType("timestamp with time zone").HasColumnName("dt_grade");
            b.Property<DateTime?>("DtSitStat").HasColumnType("timestamp with time zone").HasColumnName("dt_sitstat");
            b.Property<DateTime?>("DtTitul").HasColumnType("timestamp with time zone").HasColumnName("dt_titul");
            b.Property<int?>("Echelon").HasColumnType("integer").HasColumnName("echelon");
            b.Property<string>("Genre").HasColumnType("text").HasColumnName("genre");
            b.Property<string>("IdLastAnnee").HasColumnType("text").HasColumnName("id_last_annee");
            b.Property<int?>("IdTech").HasColumnType("integer").HasColumnName("id_tech");
            b.Property<DateTime>("ImportedAt").HasColumnType("timestamp with time zone").HasColumnName("imported_at");
            b.Property<int?>("JourNais").HasColumnType("integer").HasColumnName("jour_nais");
            b.Property<string>("LieuNais").HasColumnType("text").HasColumnName("lieu_nais");
            b.Property<string>("Modavgra").HasColumnType("text").HasColumnName("modavgra");
            b.Property<int?>("MoisNais").HasColumnType("integer").HasColumnName("mois_nais");
            b.Property<string>("NomArabe").HasColumnType("text").HasColumnName("nom_arabe");
            b.Property<string>("NomLatin").HasColumnType("text").HasColumnName("nom_latin");
            b.Property<string>("PrenomArabe").HasColumnType("text").HasColumnName("prenom_arabe");
            b.Property<string>("PrenomLatin").HasColumnType("text").HasColumnName("prenom_latin");
            b.Property<int?>("NumAffil").HasColumnType("integer").HasColumnName("num_affil");
            b.Property<int?>("NumImma").HasColumnType("integer").HasColumnName("num_imma");
            b.Property<string>("SitFam").HasColumnType("text").HasColumnName("sit_fam");
            b.Property<string>("TelPortable").HasColumnType("text").HasColumnName("tel_portable");
            b.Property<string>("Ville").HasColumnType("text").HasColumnName("ville");
            b.Property<string>("VilleForm").HasColumnType("text").HasColumnName("villeform");

            b.HasKey("Ppr");
            b.ToTable("personnel");
        });

        modelBuilder.Entity("MyAvaloniaApp.Models.Activite", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasColumnName("id")
                .HasAnnotation("Npgsql:ValueGenerationStrategy",
                    Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<bool?>("ActivPrinc").HasColumnType("boolean").HasColumnName("activ_princ");
            b.Property<string>("CiNa").HasColumnType("text").HasColumnName("cina");
            b.Property<string>("CdCycle").HasColumnType("text").HasColumnName("cd_cycle");
            b.Property<int?>("CdDivision").HasColumnType("integer").HasColumnName("cd_division");
            b.Property<int?>("CdEntAdm").HasColumnType("integer").HasColumnName("cd_entadm");
            b.Property<string>("CdEtab").HasColumnType("text").HasColumnName("cd_etab");
            b.Property<string>("CdFonc").HasColumnType("text").HasColumnName("cd_fonc");
            b.Property<string>("CdModaffe").HasColumnType("text").HasColumnName("cd_modaffe");
            b.Property<int?>("CdService").HasColumnType("integer").HasColumnName("cd_service");
            b.Property<DateTime?>("DateAffect").HasColumnType("timestamp with time zone").HasColumnName("dateaffect");
            b.Property<DateTime?>("DtAffEtab").HasColumnType("timestamp with time zone").HasColumnName("dt_aff_etab");
            b.Property<DateTime?>("DtAffPoste").HasColumnType("timestamp with time zone").HasColumnName("dt_aff_poste");
            b.Property<DateTime?>("DtAffProv").HasColumnType("timestamp with time zone").HasColumnName("dt_aff_prov");
            b.Property<DateTime?>("DtAffReg").HasColumnType("timestamp with time zone").HasColumnName("dt_aff_reg");
            b.Property<DateTime?>("DtDebExercice").HasColumnType("timestamp with time zone").HasColumnName("dt_deb_exercice");
            b.Property<DateTime?>("DtFinExercice").HasColumnType("timestamp with time zone").HasColumnName("dt_fin_exercice");
            b.Property<int?>("Ppr").HasColumnType("integer").HasColumnName("ppr");

            b.HasKey("Id");
            b.HasIndex("Ppr");
            b.ToTable("activites");
        });

        modelBuilder.Entity("MyAvaloniaApp.Models.Activite", b =>
        {
            b.HasOne("MyAvaloniaApp.Models.Personnel", "Personnel")
                .WithMany()
                .HasForeignKey("Ppr")
                .OnDelete(DeleteBehavior.Cascade);

            b.Navigation("Personnel");
        });
#pragma warning restore 612, 618
    }
}