// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using MyAvaloniaApp.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure;

#nullable disable

namespace MyAvaloniaApp.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.3")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.UseIdentityByDefaultColumns();

        modelBuilder.Entity("MyAvaloniaApp.Models.Activite", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnName("id");
            b.Property<bool?>("ActivPrinc").HasColumnName("activ_princ");
            b.Property<string>("CiNa").HasColumnName("cina");
            b.Property<string>("CdCycle").HasColumnName("cd_cycle");
            b.Property<string>("CdDivision").HasColumnName("cd_division");
            b.Property<string>("CdEntAdm").HasColumnName("cd_entadm");
            b.Property<string>("CdEtab").HasColumnName("cd_etab");
            b.Property<string>("CdFonc").HasColumnName("cd_fonc");
            b.Property<string>("CdModaffe").HasColumnName("cd_modaffe");
            b.Property<string>("CdService").HasColumnName("cd_service");
            b.Property<DateTime?>("DateAffect").HasColumnName("dateaffect");
            b.Property<DateTime?>("DtAffEtab").HasColumnName("dt_aff_etab");
            b.Property<DateTime?>("DtAffPoste").HasColumnName("dt_aff_poste");
            b.Property<DateTime?>("DtAffProv").HasColumnName("dt_aff_prov");
            b.Property<DateTime?>("DtAffReg").HasColumnName("dt_aff_reg");
            b.Property<DateTime?>("DtDebExercice").HasColumnName("dt_deb_exercice");
            b.Property<DateTime?>("DtFinExercice").HasColumnName("dt_fin_exercice");
            b.Property<int?>("Ppr").HasColumnName("ppr");
            b.HasKey("Id");
            b.HasIndex("Ppr");
            b.ToTable("activites");
        });

        modelBuilder.Entity("MyAvaloniaApp.Models.Personnel", b =>
        {
            b.Property<int>("Ppr").ValueGeneratedNever().HasColumnName("ppr");
            b.Property<DateTime?>("AncAdm").HasColumnName("anc_adm");
            b.Property<DateTime?>("AncEchelon").HasColumnName("anc_echelon");
            b.Property<DateTime?>("AncGrade").HasColumnName("anc_grade");
            b.Property<string>("Adresse").HasColumnName("adresse");
            b.Property<string>("AdresseElec").HasColumnName("adresse_elec");
            b.Property<bool?>("AffectationPrinc").HasColumnName("affectation_princ");
            b.Property<bool?>("Affilie").HasColumnName("affilie");
            b.Property<int?>("AnNais").HasColumnName("an_nais");
            b.Property<string>("CdCadre").HasColumnName("cd_cadre");
            b.Property<string>("CdDipp").HasColumnName("cd_dipp");
            b.Property<string>("CdDips").HasColumnName("cd_dips");
            b.Property<string>("CdDiscip").HasColumnName("cd_discip");
            b.Property<string>("CdGrade").HasColumnName("cd_grade");
            b.Property<string>("CdLastEtab").HasColumnName("cd_last_etab");
            b.Property<string>("CdLastFonc").HasColumnName("cd_last_fonc");
            b.Property<string>("CdNation").HasColumnName("cd_nation");
            b.Property<string>("CdPosition").HasColumnName("cd_position");
            b.Property<string>("CdStatut").HasColumnName("cd_statut");
            b.Property<string>("CiNa").HasColumnName("cina");
            b.Property<int?>("CiNn").HasColumnName("cinn");
            b.Property<int?>("CodePostal").HasColumnName("code_postal");
            b.Property<DateTime?>("DateAffil").HasColumnName("dateaffil");
            b.Property<DateTime?>("DatePosition").HasColumnName("date_position");
            b.Property<DateTime?>("DateRec").HasColumnName("date_rec");
            b.Property<DateTime?>("DateSitFam").HasColumnName("date_sitfam");
            b.Property<DateTime?>("DtCadre").HasColumnName("dt_cadre");
            b.Property<DateTime?>("DtDipProf").HasColumnName("dt_dipprof");
            b.Property<DateTime?>("DtDipScol").HasColumnName("dt_dipscol");
            b.Property<DateTime?>("DtEchelon").HasColumnName("dt_echelon");
            b.Property<DateTime?>("DtGrade").HasColumnName("dt_grade");
            b.Property<DateTime?>("DtSitStat").HasColumnName("dt_sitstat");
            b.Property<DateTime?>("DtTitul").HasColumnName("dt_titul");
            b.Property<int?>("Echelon").HasColumnName("echelon");
            b.Property<string>("Genre").HasColumnName("genre");
            b.Property<string>("IdLastAnnee").HasColumnName("id_last_annee");
            b.Property<int?>("IdTech").HasColumnName("id_tech");
            b.Property<DateTime>("ImportedAt").HasColumnName("imported_at");
            b.Property<int?>("JourNais").HasColumnName("jour_nais");
            b.Property<string>("LieuNais").HasColumnName("lieu_nais");
            b.Property<string>("Modavgra").HasColumnName("modavgra");
            b.Property<int?>("MoisNais").HasColumnName("mois_nais");
            b.Property<string>("NomArabe").HasColumnName("nom_arabe");
            b.Property<string>("NomLatin").HasColumnName("nom_latin");
            b.Property<string>("PrenomArabe").HasColumnName("prenom_arabe");
            b.Property<string>("PrenomLatin").HasColumnName("prenom_latin");
            b.Property<int?>("NumAffil").HasColumnName("num_affil");
            b.Property<int?>("NumImma").HasColumnName("num_imma");
            b.Property<string>("SitFam").HasColumnName("sit_fam");
            b.Property<string>("TelPortable").HasColumnName("tel_portable");
            b.Property<string>("Ville").HasColumnName("ville");
            b.Property<string>("VilleForm").HasColumnName("villeform");
            b.HasKey("Ppr");
            b.ToTable("personnel");
        });

        modelBuilder.Entity("MyAvaloniaApp.Models.Activite", b =>
        {
            b.HasOne("MyAvaloniaApp.Models.Personnel", "Personnel")
             .WithMany()
             .HasForeignKey("Ppr")
             .OnDelete(DeleteBehavior.Cascade);
            b.Navigation("Personnel");
        });
#pragma warning restore 612, 618
    }
}